### ISSUE TITLE
SHFill and Shading support

### ISSUE THREAD

**Issue by alecazam** [libharu/libharu#102]
This is needed for gradients and complex fills.

**Comment by dlonie** [comment]
Has anyone taken a look at this? I need shaded triangles for my project and will take a stab at implementing them, but figure I should check for previous work first :)

**Comment by chakani** [comment]
I will offer to pay someone to implement this. Gimme a quote.

**Comment by chakani** [comment]
I'm hiring someone to do this this summer. Will contribute the code when it's done.

**Comment by allisonvacanti** [comment]
@chakani I just want to point out #157, which adds support for shaded triangles. This has been working well for us in VTK, and might be useful for your work as well.

As a heads up, it appears that this project is not maintained and any contributions will stay in the merge request stage.

**Comment by StefanBruens** [comment]
@allisonvacanti  - as @tony2001 apparently has lost interest in libharu, probably the best way forward is to create a fork and become the new defacto upstream.

**Comment by bramton** [comment]
PR #157 has been merged into the devel branch.
