### ISSUE TITLE
Running ./buildconf.sh to get the config script no working

### ISSUE THREAD

**Issue by harry-takhar** [libharu/libharu#119]
When I run ./buildconf.sh into RHEL I get the following error:

autom4te: m4sugar/m4sugar.m4: no such file or directory
aclocal: autom4te failed with exit status: 1
make: *** [aclocal.m4] Error 1

Any ideas on how to resolve the issue?

**Comment by rzst** [comment]
Please try installing working autotools.

**Comment by harry-takhar** [comment]
I am not sure what you mean. But I think I have managed to fix the issue with m4sugar but now I am getting the following error messages when I run ./buildconf.sh:

autom4te: /bin/m4 failed with exit status: 1
aclocal: autom4te failed with exit status: 1
make: *** [aclocal.m4] Error 1

Any ideas on how to resolve the issue?
