### ISSUE TITLE
How to compile the demo?

### ISSUE THREAD

**Issue by manyeung** [libharu/libharu#126]
I am trying to compile the demo

`gcc arc_demo.c -lhpdf`

The message shown:
```
/tmp/ccqzRbed.o: In function `main':
arc_demo.c:(.text+0x16f): undefined reference to `print_grid'
collect2: error: ld returned 1 exit status
```

how to include the grid_sheet.h from gcc?

gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)

**Comment by luisRubiera** [comment]
2018,  having this issue, with text_demo, this library has no documentation on how to compile with it, 
```
/libharu-libharu-d84867e/demo$ gcc text_demo.c -I ../include/  -lhpdf -L/usr/lib/x86_64-linux-gnu  -lm -o text_demo_res.o
/tmp/ccTkHPps.o: In function `main':
text_demo.c:(.text+0x3f0): undefined reference to `print_grid'
collect2: error: ld returned 1 exit status
```

**Comment by gentooza** [comment]
hi!

arc_demo.c includes grid_sheet.h which defines print_grid function

having arc_demo.c, grid_sheet.c grid_sheet.h together and executing:

`gcc arc_demo.c grid_sheet.c -o arc_demo -lhpdf`

works for me
