### ISSUE TITLE
How to use the libharuto generate PDF \ a file?

### ISSUE THREAD

**Issue by dubinga** [libharu/libharu#127]
As the title.

**Comment by Clifspeare** [comment]
Perhaps you should read the documentation.  It is stellar.  I have no experience with this, and was able to understand and use libharu in my application.

**Comment by Clifspeare** [comment]
PDF/a is a standard.

**Comment by Clifspeare** [comment]
Check the hpdf_pdfa header file.

**Comment by avsokolov** [comment]
Can you provide more information or add an example how to use it?

**Comment by Clifspeare** [comment]
Their documentation is pretty good, as here: https://github.com/libharu/libharu/wiki
Essentially, you create an object representing a pdf file, then add the various page and text/image elements to it.  Then it provides the functionality to save it to a file or byte stream.
