### ISSUE TITLE
Issue with building Libharu VS2015 C++ windows form

### ISSUE THREAD

**Issue by Tieske909090** [libharu/libharu#135]
Hello all,

I have a VS2015 C++ CLR project (made acc. the top answer, option 2 [HERE](http://stackoverflow.com/questions/32404247/cant-find-windows-forms-application-for-c)). 
I tried to implement the LibHaru library in different ways, but all without success:

1. Pre-build DLL (from [HERE](https://schrievkrom.wordpress.com/2012/01/25/libharu-windows-build-for-2-3-0rc2/)):
   - Copy 'libhpdf.dll' to the project folder
   - In VS:   Add -> Reference -> libhpdf.dll
   - I get the error: Could not add a reference to '... libhpdf.dll' as it is not of a type or version current project can use

2. Build [libharu](https://github.com/libharu/libharu) myself:

From the Libharu wiki ([HERE](https://github.com/libharu/libharu/wiki/Installation)) I do the following:

Start 'VS2015 x86 Native Tools Command Prompt' -> cd to libharu folder.
Enter command; "nmake -f script/Makefile.msvc_dll" (as I want to distribute my simple program with the dll)
I get the error cannot open include file 'zlib.h'

So I tried to zlib myself, which failed:
   - [zlib](http://www.zlib.net/):
      - from 'zlib-1.2.8/win32/VisualC.txt': To build zlib using the Microsoft Visual C++ environment, use the appropriate project from the projects/ directory.
      - I cannot find the projects/ directory in zlib-1.2.8. Therefore, I do not build zlib myself here.

So I move on to libpng (which I read needs to be also built together with zlib to work for libharu):
   - [libpng](http://www.libpng.org/pub/png/libpng.html):
      - I open 'lpng1624/projects/vstudio/vstudio.sln', and build all with Release -> Win32
      - Rebuild All: 7 succeeded (after commenting out the //#ifdef PNG_FREESTANDING_TESTS lines in pngvalid.c, pngtest.c and pngunknown.c)

   - libharu: 
      - I go to libharu-master\script\Makefile.msvc_dll and change the following text (to point to the correct folder finding zlib.h, zlib.dll, libpng13.lib and zlib.lib:
```
PNG_PREFIX   = ../../libpng
*to*   PNG_PREFIX   = ../lpng1624
ZLIB_PREFIX   = ../../zlib
*to*   ZLIB_PREFIX   = ../zlib-1.2.8
CFLAGS=/MD -nologo -O2 -Iinclude -Iwin32\include   -I"$(PNG_PREFIX)"\include -I"$(ZLIB_PREFIX)"\include -DHPDF_DLL_MAKE
*to*   CFLAGS=/MD -nologo -O2 -Iinclude -Iwin32\include   -I"$(PNG_PREFIX)" -I"$(ZLIB_PREFIX)" -DHPDF_DLL_MAKE
LDFLAGS= /LIBPATH:$(PNG_PREFIX)\lib /LIBPATH:$(ZLIB_PREFIX)\lib /LIBPATH:win32\msvc libpng13.lib zlib.lib
*to*   LDFLAGS= /LIBPATH:$(PNG_PREFIX)\projects\vstudio\Release /LIBPATH:$(ZLIB_PREFIX) /LIBPATH:win32\msvc libpng16.lib zlib.lib

```

   - Again, Start 'VS2015 x86 Native Tools Command Prompt' -> cd to libharu folder.
   - Enter command; "nmake -f script/Makefile.msvc_dll"
   - I get the following error, after which I am lost:

```
libhpdf.def : error lnk2001: unresolved external symbol HPDF_3DAnnot_Set3DView
libhpdf.lib : fatal error lnk1120: 1 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\link.exe"' : return code '0x460'
```

Am I doing something wrong or missing something? I have been trying 2 days now to get this working, but I am lost.
I want to achieve the same as displayed in this youtube video, so when a Button is pushed on the WindowsForm, a PDF will be generated with some output text and a picture.

**Comment by termi3** [comment]
It is linker error, so the linker does not find the compiled libharu (not the dll!)
in the solution explorer, go to properties of your project, -> Configuration propertis ->Linker ->Input -> Additional Dependencie and you should find there 
libhpdfd.lib in the debug version or   libhpdf.lib in the release.
Do you see these?

**Comment by Tieske909090** [comment]
I have not linked my project to the libhpdfd.lib (or libhpdf.lib) yet.
I think I still need to compile these first with Libharu?
At least I cannot find these files in the libharu-master folder at this stage.

**Comment by termi3** [comment]
That is the problem.
You first compile libharu in the same way as zlib and libpng, than it is for you a library like these, 
and then you link your project to it.
Keep in mind, the libs and your project should be compiled with the same compiler (and options).
In your case I would recomend using some system like CMake, Premake or similar. 
I have to work with cmake and libharu do this well. 
You install cmake, than you run it and open the source folder where CMakeLists.txt file is,
and select DIFFERENT folder for the binaries (for instance libharu_vs2015)
Then press configure so many times until there is no more red position.
You will need to set the paths to zlib and png include files and libraries. (and press configure again)
When you get it "done", press generate and you will have solution file for your visual studio.
Open it with VS and compile.
Then it make sence to have as well cmake prearation for your project see this here
https://cmake.org/cmake-tutorial/
you will have to add
FIND_PACKAGE(libhpdfs REQUIRED) 
to find the location

this to include
INCLUDE_DIRECTORIES( ${LIBHPDF_INCLUDE_DIRS})

this this to add the linker
TARGET_LINK_LIBRARIES(YourprojectName
	${LIBHPDF_LIBRARIES}
	}
and then you can get solution file for your project with all dependencies correct (as for the libharu).

You can try the same with premake it is more simple, but it does not give alway what is missing.
It is somehow longer way you have to learn, but if you have to work with libraries and to work on different computers / operation systems, is one reasanable way

**Comment by Tieske909090** [comment]
Thank you termi3!
I finally got it working.

The steps I took are the following:

**CMake**
1. Download CMake:     (cmake-3.6.1-win64-x64.zip [HERE](https://cmake.org/download/))

**ZLIB**
2.1. Download ZLIB:    (zlib-1.2.8.zip [HERE](http://www.zlib.net/))
2.2. RENAME ZLIB-1.2.8 to ZLIB!!!
2.3. Run CMake
2.4. Open and build zlib.sln

**LibPNG**
3.1 Download LibPNG:    (lpng1624.zip [HERE](http://www.libpng.org/pub/png/libpng.html))
3.2. Add ZLIB_INCLUDE_DIR and ZLIB_LIBRARY with the use of CMAKE.
Mark ADVANCED IN THE TOP, OTHERWISE IT WILL NOT ACCEPT ZLIB_INCLUDE_DIR
3.3. Run CMake
3.4 Add configuration parameters
3.5	Inside the ZLIB folder, copy zconf.h from the original zip-file (for some reason zconf.h becomes zconf.h.cmakein?)
3.6 	Open and build libpng.sln

**LibHaru**
4.1. Download LibHaru    (libharu-master.zip [HERE](https://github.com/libharu/libharu))
4.2. RENAME libharu-master to libharu!!!!
4.3. Run CMake:
4.4. Open libharu.sln

**My Project**
5.1 Open my project in Visual Studio
5.2. Add my .dll's as reference (reminder for myself, nothing to do with this 'tutorial')
5.3  Add the following information to the project configuration properties:

VC++ Directories:
- Include directories (for .h files):
- Library directories (for .lib files):
- Linker -> Input (.lib files)

I also generated a .pdf with more screenshots of the process, and the code that I used to test if LibHaru was working for my project ([Libharu with VS2015.pdf](https://github.com/libharu/libharu/files/435690/Libharu.with.VS2015.pdf)).
Hopefully this will also be of help for others.

For my project I do not use a CMakeList yet, but I might implement this in the near future.
Again, thank you for the support.

**Comment by termi3** [comment]
Great :+1: 
Can you try to close this ticket?
I think, I have to make a fork of the project, in order to be able to make corrections of it, here I have no rights.

**Comment by termi3** [comment]
By the way, you can tell to CMakeLIsts as well to look for the folder of your dll's so that you do not need to copy these manually.

**Comment by samkots** [comment]
Also, file `hpdf_config.h` will be generated in the your `<BUILD_DIR>/include` directory. You need to copy this file to the `include` directory of your installation location.

**Comment by dinhanhx** [comment]
@Tieske909090 Hello sir, so I followed your instructions but for Visual Studio 2017. 
When I run your code to test, I get "Unresolved External Symbol" erros.

This is my project propery page
![image](https://user-images.githubusercontent.com/38489776/75334416-6cc17300-58ba-11ea-9369-c03804ad03f8.png)
![image](https://user-images.githubusercontent.com/38489776/75334575-aeeab480-58ba-11ea-802f-d529b6ac31b4.png)
![image](https://user-images.githubusercontent.com/38489776/75334603-bc07a380-58ba-11ea-8a99-30513ffa337c.png)
![image](https://user-images.githubusercontent.com/38489776/75334641-caee5600-58ba-11ea-8422-b76cc1c0d42a.png)
etc..
![image](https://user-images.githubusercontent.com/38489776/75334668-d6da1800-58ba-11ea-95b2-b4f4d4ae2ade.png)
etc..
![image](https://user-images.githubusercontent.com/38489776/75334717-ea857e80-58ba-11ea-958f-e1a4756eb053.png)
![image](https://user-images.githubusercontent.com/38489776/75334906-359f9180-58bb-11ea-9006-a25d493f6ba0.png)
![image](https://user-images.githubusercontent.com/38489776/75334938-4223ea00-58bb-11ea-9085-35aec0319f8f.png)
![image](https://user-images.githubusercontent.com/38489776/75334963-4d771580-58bb-11ea-8294-46d3a5a3440d.png)

When I run the code
![image](https://user-images.githubusercontent.com/38489776/75335006-61bb1280-58bb-11ea-9ef6-8363868a2273.png)

I perceived that I am missing  lib file(s) but I can not figure out. Can you please kindly help me?

**Comment by gekkehenkie11** [comment]
I was about to throw my PC out of the window, you saved my day man!! Just one small changes, maybe it's the version but I don't have (nor need) libhpdf.lib and libhpdfs.lib, mine built haru.lib which works fine. 

Also not in your tutorial was that it complained about a missing cmake directory (I think it was headers), not sure what this is about I just checked it, it's empty.

Anyway, you're the best made, thanks!

**Comment by Basilisvirus** [comment]
@samkots you said I should copy `hpdf_config.h` from `<BUILD_DIR>/include` to the include directory of my installation location. My installation location of what? 

I want to "install" libharu, so my installed location is the `<BUILD_DIR>`

**Comment by musvaage** [comment]
@Basilisvirus

Some dated content on a zlib build [here](https://nurmi-labs.blogspot.com/2017/05/9pvfs.html); I wouldn't be in a position to help further.

**Comment by Basilisvirus** [comment]
I followed @Tieske909090 's notes, managed to compile the library and updated the notes into pdfs:

[Zlib Compile how to.pdf](https://github.com/libharu/libharu/files/9779398/Zlib.Compile.how.to.pdf)
[libpng Compile how to.pdf](https://github.com/libharu/libharu/files/9779399/libpng.Compile.how.to.pdf)
[libharu Compile how to.pdf](https://github.com/libharu/libharu/files/9779424/libharu.Compile.how.to.pdf)
