### ISSUE TITLE
How can to display ñÑáéíóú characters

### ISSUE THREAD

**Issue by joseluis8906** [libharu/libharu#144]
How can to display special spanish characters, I have been testing all encodings and the document doesn't display spanish special characters (áéíóúñ), help please.

**Comment by gentooza** [comment]
I've the same need @joseluis8906!

looking at libharu encondings there is neither UTF-8 nor ISO8859-1 latin enconding available.
[https://github.com/libharu/libharu/wiki/Encodings](https://github.com/libharu/libharu/wiki/Encodings)
:-/
<s>googling</s> duckduckgoing a bit in the internet, I've seen some info about code to add UTF-8 support to libharu... (I'll try it)

cheers

**Comment by daB0bby** [comment]
Check out my answer here: #27
