### ISSUE TITLE
Proper README Markdown?

### ISSUE THREAD

**Issue by samuel-allan** [libharu/libharu#152]
What a great repository!
I was just wondering, is there any particular reason why the markdown is formatted without all the rich features GitHub markdown offers? (such as titles, subtitles, [here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) is a great preview/guide).

Thanks again, happy to be reporting a possible issue :)

**Comment by bramton** [comment]
This has been addressed in the devel branch.
