### ISSUE TITLE
Overwrite a PDF file that is open

### ISSUE THREAD

**Issue by ryklin** [libharu/libharu#154]
If a file is open when calling :

HPDF_STATUS result = HPDF_SaveToFile(pdf, fileName);

The result == 4119

In this case I implemented a message to the user that the file is open and must be manually closed first.

I suppose there is no way to address this problem. Since a PDF can be opened in any reader program, I can not know which process to programmatically kill, then try to save again.

Any ideas/feedback?

Thanks and wonderful library, bullet-proof so far! I have generated customized PDFs for making reports with charts, images, text, and grids! Everything was very easy to do, instructions were clear to follow, I compiled everything in C++/Visual Studio 2015.

**Comment by drsurfer** [comment]
In every situation I can imagine, what you suggest (killing a process, if you are able to find the right one) is simply absurd and against the good practice.

If an user has opened your file, or he is copying it to a slow media or whatever, the solution is to manage the conflict in a user friendly way. You should NOT prompt to close that file, or kill anyone, but you could inform the user of the problem, and offer some alternatives. 
For example to retry (may be after closing the file), to save with a new name or to cancel at all the operation.

**Comment by ryklin** [comment]
Thanks for the feedback.
