### ISSUE TITLE
Flush a PDF?

### ISSUE THREAD

**Issue by domfe** [libharu/libharu#155]
Hello.
Is there a way to flush the PDF content to disk and continue adding pages?
I have to create a huge PDF file and on small systems it fills the memory. When this happens the document creation takes a lot of time and becomes almost unbearable.
So I'm looking for a way to generate some pages, save to disk, free some memory, then generate other pages, flush and so on.

Thank you

**Comment by r1me** [comment]
Sadly, it won't be possible. This topic was mentioned already on libHaru group: https://groups.google.com/d/msg/libharu/9SH_NCCbQUI/gS9cTzzqAwAJ
