### ISSUE TITLE
Attaching files is broken. (Fix patch included)

### ISSUE THREAD

**Issue by hvanbrug** [libharu/libharu#159]
The PDF spec is very specific about Name Trees being sorted correctly. Because of this, several PDF viewers have come to rely on that fact and will not work properly if the tree is sorted incorrectly. When attaching files, I was able to actually crash Adobe Reader and Adobe Acrobat DC Pro just because the name tree was wrong. There were two problems with it:
1. The sort was not sorting in the correct order
2. When inserting names into the middle of the tree it would always corrupt the list for that name tree because it would only insert the name, and not the object.

These are the issues that I found and fixed to make attaching files work again:

- Insertion sort was broken. Walking backwards through the list to find the first item we are smaller than is incorrect because the list is supposed to be sorted in ascending order.

- String comparison was broken. You are supposed to only compare the string length if the content of both strings is the same up to the point of the shorter string.

- Inserting into an array was broken. We search through the list, assigning each element to 'ptr', and then compare it to  'target'. When checking if the list item is a proxy you weren't looking at 'ptr' but instead 'obj'. This was corrupting the name tree when you inserted into because it would be able to insert the name, but never the value.

[libharu_changes.patch.zip](https://github.com/libharu/libharu/files/1050676/libharu_changes.patch.zip)

**Comment by bramton** [comment]
A belated thank you! The provided patch from has been merged (393aa61d55d1132339e64db7aa95976ce5f6c3b2) into the devel branch, better late than never.

Closes #73
