### ISSUE TITLE
HPDF_Page_CreateXObjectFromImage last argument has wrong type

### ISSUE THREAD

**Issue by mvidiassov** [libharu/libharu#172]
The last argument of `HPDF_Page_CreateXObjectFromImage` is `HPDF_Boolean  zoom`.
But it is used only once in
`   if (zoom)`
so the proper type for it seems to be HPDF_BOOL.

**Comment by samkots** [comment]
Yes! This is causing build failure on Windows for me(identifier error for HPDF_Boolean).
Is anyone able to build libHaru on Windows?

**Comment by chakani** [comment]
I am able to build libHaru on Windows, although I don't know if I have the same version as you.

`HPDF_Boolean` is defined as:

    typedef struct _HPDF_Boolean_Rec  *HPDF_Boolean;

It's a pointer to a struct, so it's testing for NULL, not bool.

**Comment by samkots** [comment]
How?? I had to comment the function declaration on line `459` of `hpdf.h`:
`//HPDF_EXPORT(HPDF_XObject)
//HPDF_Page_CreateXObjectFromImage    (HPDF_Doc       pdf,
//                                     HPDF_Page      page,
//                                     HPDF_Rect      rect,
//                                     HPDF_Image     image,
//                                     HPDF_Boolean   zoom);`

**Comment by samkots** [comment]
Ok I got it working.
Just don't define the flag `HPDF_DLL` in your client app. This makes `HPDF_SHARED` undefined and enables the [#else here](https://github.com/libharu/libharu/blob/d84867ebf9f3de6afd661d2cdaff102457fbc371/include/hpdf.h#L81) which includes `hpdf_pdfa.h` which in turns includes `hpdf_objects.h`.

In [CMakeLists.txt](https://github.com/libharu/libharu/blob/d84867ebf9f3de6afd661d2cdaff102457fbc371/demo/CMakeLists.txt#L53) of demo codes, `HPDF_DLL` is defined. Is that wrong?

**Comment by bramton** [comment]
Fixed by #189.
