### ISSUE TITLE
Obsolete version information in CMakeLists.txt

### ISSUE THREAD

**Issue by mvidiassov** [libharu/libharu#173]
It seems LIBHPDF_MINOR is being incorrectly set.
```
# information about libharu
set(LIBHPDF_MAJOR 2)
set(LIBHPDF_MINOR 2)
set(LIBHPDF_PATCH 0)
```

**Comment by lelandyang** [comment]
and so is the cass in the resource file.
The src code version is 2.4.0. 
But I suppose no one is gonna correct it before the new maintainer appears cause the author declared maintanance termanation and is calling for a new maintainer.

**Comment by bramton** [comment]
This has been updated in the devel branch.
