### ISSUE TITLE
What is the point of the errors "detail codes" ?

### ISSUE THREAD

**Issue by Hurlu** [libharu/libharu#178]
Been recently using libharu, and one thing that has striken me is that you can get some "detail codes" with your error code, but there is not any way to extract info from them.
Does someone know about them? Thanks !

**Comment by yimin-nv** [comment]
It is refer to system errno, you can get details by
    `printf("%s", strerror(errno));`

**Comment by Hurlu** [comment]
Alright, I added a sentence to clarify it in the wiki, thanks !
