### ISSUE TITLE
Value parameter measured in...?

### ISSUE THREAD

**Issue by UNiXMIT** [libharu/libharu#179]
I am very doubtful that I will get a reply on here now but worth a try.
One of the parameters for HPDF_Page_SetHeight() is Value - "value - The new page height. Valid values are between 3 and 14400."

My question is what is the unit of length? mm, inches, pixels?

Thanks

**Comment by termi3** [comment]
Hi, there were some information about that in the web and as far as I remember it was in pixels.
If you have 72 dpi, then you can calculate the heigth.
in your case I will just test it quicly with some of the test examples, I use standard page and did not changed this

**Comment by chakani** [comment]
All Haru units are printer's points (72 points/inch). Not pixels. PDF is independent of resolution.

14400 units (points) is 200 inches, the maximum size of a PDF document.

**Comment by UNiXMIT** [comment]
Thanks for your help. That is great.
