### ISSUE TITLE
What is the meaning of Font measurements

### ISSUE THREAD

**Issue by TheMidgardWatcher** [libharu/libharu#188]
He there,

I'm trying to calculate height of my text before actually rendering it on a page, and I'm using methods: HPDF_Font_GetAscent() and HPDF_Font_GetDescent(). And I'm a bit confused bu result values for Helvetica typeface:
Ascent: 718
Descent: -207
I assume that 0 is the Baseline

But what this values mean? How could I re-calculate them into standard document units, which are points with 72dpi?

I would appreciate it if someone could help me with this..

**Comment by chakani** [comment]
The units are thousandths of a points. You need to divide by 1000. to get points (72 points/inch).

This is what the functions return:

![haru - font parts](https://user-images.githubusercontent.com/5422023/46907652-1ed9e400-ceec-11e8-8e5a-5897968d5d34.png)

Note that the X-height function seems to return half the height, you have to multiply by 2.

**Comment by TheMidgardWatcher** [comment]
Thanks for the clarification! But 1000 is a constant for all fonts types even loaded from tts or only for built-in ones?

**Comment by chakani** [comment]
I believe it is constant for all fonts. It's also called "units per em", where 'em' is a space equal in width to the letter 'M'. There is also an 'en' space and 'thin space'.

**Comment by TheMidgardWatcher** [comment]
Thanks guys for your help! I think I've found answers on my questions.

**Comment by TheMidgardWatcher** [comment]
Sorry, I've thought about that and got one more question, how to calculate this values for different sizes of the font?

**Comment by chakani** [comment]
Multiply by the point size and divide by 1000.

**Comment by TheMidgardWatcher** [comment]
Sorry, I'm new to this fonts and typographical stuff. What do you mean by point size? Size of font in points?

**Comment by chakani** [comment]
Yes, the size of the font in points. 72 points = 1 inch.

The point is an archaic unit of measurement used in the printing industry since 1517.

See https://en.wikipedia.org/wiki/Point_(typography)

**Comment by TheMidgardWatcher** [comment]
Thanks, I think I've got it.
