### ISSUE TITLE
Issue with implementing Libharu in Visual Studio 2017

### ISSUE THREAD

**Issue by dinhanhx** [libharu/libharu#208]
@Tieske909090 Hello sir, so I followed your instructions but for Visual Studio 2017. 
When I run your code to test, I get "Unresolved External Symbol" erros.

This is my project propery page
![image](https://user-images.githubusercontent.com/38489776/75334416-6cc17300-58ba-11ea-9369-c03804ad03f8.png)
![image](https://user-images.githubusercontent.com/38489776/75334575-aeeab480-58ba-11ea-802f-d529b6ac31b4.png)
![image](https://user-images.githubusercontent.com/38489776/75334603-bc07a380-58ba-11ea-8a99-30513ffa337c.png)
![image](https://user-images.githubusercontent.com/38489776/75334641-caee5600-58ba-11ea-8422-b76cc1c0d42a.png)
etc..
![image](https://user-images.githubusercontent.com/38489776/75334668-d6da1800-58ba-11ea-95b2-b4f4d4ae2ade.png)
etc..
![image](https://user-images.githubusercontent.com/38489776/75334717-ea857e80-58ba-11ea-958f-e1a4756eb053.png)
![image](https://user-images.githubusercontent.com/38489776/75334906-359f9180-58bb-11ea-9006-a25d493f6ba0.png)
![image](https://user-images.githubusercontent.com/38489776/75334938-4223ea00-58bb-11ea-9085-35aec0319f8f.png)
![image](https://user-images.githubusercontent.com/38489776/75334963-4d771580-58bb-11ea-8294-46d3a5a3440d.png)

When I run the code
![image](https://user-images.githubusercontent.com/38489776/75335006-61bb1280-58bb-11ea-9ef6-8363868a2273.png)

I perceived that I am missing  lib file(s) but I can not figure out. Can you please kindly help me?

_Originally posted by @dinhanhx in https://github.com/libharu/libharu/issues/135#issuecomment-591348457_

**Comment by dinhanhx** [comment]
### If you somehow read this issue thread and know how to fix it, I want to tell you "I give up trying"

**Comment by Freygeist94** [comment]
Having the same issue, tried a lot of suggested fixes that I found online, none of them worked.

**Comment by chakani** [comment]
Libharu has many dependencies: PNG, Zlib compression.

Attached is an outline of what other projects you need, and in what order to compile them.
[Haru PDF projects.pdf](https://github.com/libharu/libharu/files/4344386/Haru.PDF.projects.pdf)


I see that the undefined references are from Haru directly. Have you set an environment variable incorrectly? In what modules are the undefined functions located? (Ex: HPDF_Page_TextOut, very hard to read). Are they included in your project? Why isn't the compiler seeing them? Is there a discrepancy in the argument types?

**Comment by dinhanhx** [comment]
Thanks for your information

**Comment by bonnienihao** [comment]
Hi, Do you solve the problem, I tried a lot of suggested fixes that I found online, but none of them worked, can you give some Suggest

**Comment by dinhanhx** [comment]
I gave up long time ago due to the decrease in need of using libharu.

**Comment by BeczeT** [comment]
Hi!
I found the project three weeks ago. I managed to operate under Borland C. I took the zlib and png links from the include files and translated them. Everything works fine :). I wrote a small class that uses HPDF_Page_TextRect, HPDF_Page_LineTo, HPDF_Page_Rectangle and so on. functions.

**Comment by chakani** [comment]
Don't give up! Libharu is a bit tricky, but it is enormously valuable as a PDF library, free from the limitations of driver-based solutions. I contributed gradients my self a couple of years ago.

Understand that it is dependent on two external, separate libraries: PNG and ZLIB.

**Comment by Basilisvirus** [comment]
I followed @Tieske909090 's notes, managed to compile the library and updated the notes into pdfs:

[Zlib Compile how to.pdf](https://github.com/libharu/libharu/files/9779398/Zlib.Compile.how.to.pdf)
[libpng Compile how to.pdf](https://github.com/libharu/libharu/files/9779399/libpng.Compile.how.to.pdf)
[libharu Compile how to.pdf](https://github.com/libharu/libharu/files/9779424/libharu.Compile.how.to.pdf)
