### ISSUE TITLE
Please name release archives libharu-x.y.z again or at least vx.y.z instread of RELEASE_x_y_z

### ISSUE THREAD

**Issue by drhpc** [libharu/libharu#211]
I stumbled over the new naming scheme of release files while trying to upgrade a packaging script from 2.2.1 which used http://libharu.org/files/libharu-2.2.1.tar.gz, a nice, traditional release archive name that you also can stuff into a directory with others for local archival and mirroring.

Now I see that the release moved github, like just about anyone flocking to the same spot to host all software of the world, with the strange naming of RELEASE_2_3_0.tar.gz . I  am used already to many github releases just being in the form of a version tag, of the scheme v1.2.3.tar.gz or 1.2.3.tar.gz. It is customary (or at least I whitnessed it an am practising it myself;-) to prepend the project hame to that on mirrors, so that you have the file libharu-2.3.0.tar.gz with the URL libharu/archive/v2.3.0.tar.gz on github.

This also matches the actual release tarballs, as they usually contain a directory named project-x.y.z/. It's being nice to packagers having a source directory name that matches the archive name. The current libharu releases extract to libharu-RELEASE_x_y_z/, btw.

The unwieldy RELEASE_x_y_z is an unexpected deviation that complicates this. Is this a bare version? Is it a package named RELEASE? What about those underscores instead of dots?

Is there any technical barrier in changing at least the prefix to libharu? Even if the version stays at x_y_z, it's a bit odd, but doesn't really break anything. Or switch to the vx.y.z scheme t hat many other projects have on github …

**Comment by drhpc** [comment]
Oh, and the release tarball is broken anyway. INSTALL claims this:
```
Installation
------------

Installing libHaru on Linux/Unix is as easy as this:
./configure && make && make install
```
But there's no configure script and autoreconf also does not sound too happy. Did you switch to CMake, as there are respective files lingering? Is just the documentation outdated?

**Comment by drhpc** [comment]
Also, I adapted now to the RELEASE naming thing in the packaging and mirror scripts. But please, don't change it to a different string in future unless going for proper naming or the vx.y.z thing other projects have;-)

**Comment by bramton** [comment]
Agreed, next release will have the proper vx.y.z naming :)
