### ISSUE TITLE
Compilation fails unless explicit linking to libm is enforced

### ISSUE THREAD

**Issue by badshah400** [libharu/libharu#213]
When [building on openSUSE], we need to link against libm explicitly; otherwise, we get linker errors for missing `sincos`, `sqrt`, and other cmath functions. We currently use a patch to do this:

```diff
Index: libharu-RELEASE_2_3_0/CMakeLists.txt
===================================================================
--- libharu-RELEASE_2_3_0.orig/CMakeLists.txt
+++ libharu-RELEASE_2_3_0/CMakeLists.txt
@@ -99,6 +99,8 @@ if(PNG_FOUND)
   set(ADDITIONAL_LIBRARIES ${ADDITIONAL_LIBRARIES} ${PNG_LIBRARIES})
 endif(PNG_FOUND)
 
+find_library(M_LIB m)
+set(ADDITIONAL_LIBRARIES ${ADDITIONAL_LIBRARIES} ${M_LIB})
 
 # =======================================================================
 # configure header files, add compiler flags
```

It would be great if this were accepted upstream (I can make a pull request if you give me the go ahead) or if you have perhaps a better way of fixing this.

Thanks!

[building on openSUSE]: https://build.opensuse.org/package/show/Publishing/libharu

**Comment by mathstuf** [comment]
This should probably be behind an `if (UNIX)` guard since Windows is unlikely to take it too kindly. A PR won't hurt, but activity is low. I'd be able to cherry-pick it into VTK's import mechanism too.

**Comment by badshah400** [comment]
#214  should be it.
