### ISSUE TITLE
About building/compiling

### ISSUE THREAD

**Issue by jhernancanom** [libharu/libharu#219]
Hi, friends.
I am interested in building/compiling LibHaru from sources.
Who can give me instructions for getting this?
Thanks.

**Comment by tony2001** [comment]
Sure
Check out the docs: https://github.com/libharu/libharu/wiki/Installation

**Comment by jhernancanom** [comment]
Ok.
I wanted a little bit more helping, but... fine. 
I'll proceed.
Thanks.

**Comment by chakani** [comment]
This is not a trivial technology. If you can't figure it out, you are going to need _lots_ of help.
Attached is an overview of wha
[Haru PDF projects (1-3).pdf](https://github.com/libharu/libharu/files/5411056/Haru.PDF.projects.1-3.pdf)
t to compile and in what order, for Visual Studio/Windows

**Comment by jhernancanom** [comment]
Yes, Pierre.
That's the cause for I looked for help.
But this PDF is a list of files......
While the Wiki Installation URL provided by Dogval helps me more.... only
that it seems I need to install a lot of things....... But I'll try them.
This is the way I am going to walk....

Thanks, friends.
