### ISSUE TITLE
Can mshy.ttf be one of base14 fonttype ?

### ISSUE THREAD

**Issue by lsff** [libharu/libharu#224]
I want to reduce file size

**Comment by kalpha2** [comment]
No. The Base14 font list is set in stone, so any proper pdf viewer will have support for those 14 fonts. If the pdf is for internal use and you can guarantee that every system will have the font you use then you do not have to embed it but it will only work locally. If it is sent out then it's appearance could be dramatically altered depending on the font list a recipient's pdf viewer has available. At best it will be readable even if it doesn't look the same and in worst case it could end up looking like a set of empty boxes for every single character.

**Comment by CADAutomation** [comment]
Hello guys,

Am looking for a 3D-PDF library to create 3D-PDF from CAD files (u3d format or other CAD formats). Please let me know how far this library inline with my requirements. Will I be able to create 3D-PDF, edit and merge?. Please let me know. Thank you in advance.

**Comment by chakani** [comment]
No it won't do 3D PDF.
    
    On 31 Aug 2021 9:21 AM, CADAutomation
      wrote:
    
    
      
      Hello guys,
      Am looking for a 3D-PDF library to create 3D-PDF from CAD files
        (u3d format or other CAD formats). Please let me know how far
        this library inline with my requirements. Will I be able to
        create 3D-PDF, edit and merge?. Please let me know. Thank you in
        advance.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
        Triage notifications on the go with GitHub Mobile for iOS or Android.
        
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/libharu/libharu/issues/224#issuecomment-909185778",
"url": "https://github.com/libharu/libharu/issues/224#issuecomment-909185778",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    -- 
      Progeny Genealogy Inc. 902–681–3102
      Progeny helps you tell the Story of Your
        Family ™
      progenygenealogy.com

**Comment by CADAutomation** [comment]
Thank you for your quick response. Could you please suggest me any free library for creating 3DPDF ? Thank you

**Comment by chakani** [comment]
Other than Ghostscript and LibHaru, I'm not aware of any free PDF
      libraries. PDF is complex and expensive to program.
    
    On 31 Aug 2021 9:38 AM, CADAutomation
      wrote:
    
    
      
      Thank you for your quick response. Could you please suggest me
        any free library for creating 3DPDF ? Thank you
      —
        You are receiving this because you commented.
        Reply to this email directly, view it on GitHub, or unsubscribe.
        Triage notifications on the go with GitHub Mobile for iOS or Android.
        
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/libharu/libharu/issues/224#issuecomment-909197924",
"url": "https://github.com/libharu/libharu/issues/224#issuecomment-909197924",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    -- 
      Progeny Genealogy Inc. 902–681–3102
      Progeny helps you tell the Story of Your
        Family ™
      progenygenealogy.com

**Comment by CADAutomation** [comment]
Thank you for the information. Does Ghostscript offers any functionality to create 3D PDF? Please let me know. Thank you in advance.

**Comment by chakani** [comment]
It doesn't appear to:
    https://www.ghostscript.com/
    
    On 31 Aug 2021 9:59 AM, CADAutomation
      wrote:
    
    
      
      Thank you for the information. Does Ghostscript offers any
        functionality to create 3D PDF? Please let me know. Thank you in
        advance.
      —
        You are receiving this because you commented.
        Reply to this email directly, view it on GitHub, or unsubscribe.
        Triage notifications on the go with GitHub Mobile for iOS or Android.
        
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/libharu/libharu/issues/224#issuecomment-909212903",
"url": "https://github.com/libharu/libharu/issues/224#issuecomment-909212903",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    -- 
      Progeny Genealogy Inc. 902–681–3102
      Progeny helps you tell the Story of Your
        Family ™
      progenygenealogy.com

**Comment by lammertb** [comment]
LaTeX in combination with the media9 library will give you the functionality to create 3D PDF files with free software, but be prepared to jump back to the previous century. LaTeX is not the most modern layout software and was designed well before the WYSIWYG era.

**Comment by CADAutomation** [comment]
Thank you Chakani and Lammertb for your valuable suggestions. I will look into those. More suggestions welcomed from other members. Thank you all.
