### ISSUE TITLE
Why `hpdf_conf.h`  is misspelled

### ISSUE THREAD

**Issue by Basilisvirus** [libharu/libharu#242]
I see this often, configuration files misspelled, so that the compiler will drop an error.

In folder \libharu-2.4.2\include , the `hpdf_conf.h` file should be renamed to `hpdf_config.h` , otherwise compilation is failed, since `hpdf.h` asks for a `hpdf_config.h` file.

Why is this named like that? So that users notice this file and edit its contents to match their application?

**Comment by bramton** [comment]
The `hpdf_config.h` header file is generated by CMake from the  `hpdf_config.h.cmake` file. The `hpdf_conf.h` header file contains some static configuration defines.
