### ISSUE TITLE
where is "apdf.h" ?

### ISSUE THREAD

**Issue by Basilisvirus** [libharu/libharu#243]
In the documentation [here](http://libharu.sourceforge.net/document_handling.html#HPDF_New_HPDF_NewEX_):

For the `HPDF_New` function, the example mentions I should include `#include "apdf.h"` . Where is `apdf.h`? I cannot find it anywhere in the repository, nor when googling it.

**Comment by bramton** [comment]
The link refers to a very outdated piece of documentation. Please find the recent documentation under Wiki, here on the GitHub project page. Also have a look at the various demos provided.
