### ISSUE TITLE
Cannot actually understand how to use hpdf_version.h file. 

### ISSUE THREAD

**Issue by Basilisvirus** [libharu/libharu#244]
I tried to use NMAKE on windows via Visual studio as stated in the instructions.
I got an error, saying it could not find `hpdf_version.h` file. 
I saw there is a  `hpdf_version.h.cmake` file in the include folder.
I think this should be something that should be included in the [installation instructions
](https://github.com/libharu/libharu/wiki/Installation).
I searched the issues, not knowing what to do exactly and I ended up changing the name of the file to the name the NMAKE wants to see (aka  `hpdf_version.h`  and change its contents with [this ](https://github.com/libharu/libharu/blob/fdd021c79afaea8b2ae1a1141978ef7265869bed/include/hpdf_version.h#L3-L8)file (the hpdf_version.h file that is in the repo).
And it overcame this error, but this is what I should do? Why is the  `hpdf_version.h` file not named like that from the beginning?

**Comment by bramton** [comment]
The documentation is a bit outdated at the moment. The project now uses CMake for its build environment. CMake will generate `hpdf_version.h` for you based on the `hpdf_version.h.cmake`.
