### ISSUE TITLE
unresolved externals - building for VS 2022

### ISSUE THREAD

**Issue by Basilisvirus** [libharu/libharu#245]
I am on windows 10 and using Visual studio 2022, and running the make/cmake commands via the VStudio's power shell.
I build the libpng1.6.35 and Zlib, which I [downloaded from the github](https://github.com/madler/zlib) page.
I build the library libhary using NMAKE -f script/Makefile.msvc , according to the [installation instructions](https://github.com/libharu/libharu/wiki/Installation), and this was the output from the make file, no errors as I can tell:

```
PS C:\Users\Soldy\Documents\WindowsAppProject\imgui-docking\examples\example_glfw_vulkan\libharu-2.4.2>  NMAKE -f script/Makefile.msvc

Microsoft (R) Program Maintenance Utility Version 14.33.31629.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        cl -Fosrc\hpdf_image_png.obj -MT -nologo -O2 -Iinclude -Iwin32\include -I"../../libpng"\include -I"../../zlib"\include -c src\hpdf_image_png.c
hpdf_image_png.c
        cl -Fosrc\hpdf_image_ccitt.obj -MT -nologo -O2 -Iinclude -Iwin32\include -I"../../libpng"\include -I"../../zlib"\include -c src\hpdf_image_ccitt.c
hpdf_image_ccitt.c
        cl -Fosrc\hpdf_doc_png.obj -MT -nologo -O2 -Iinclude -Iwin32\include -I"../../libpng"\include -I"../../zlib"\include -c src\hpdf_doc_png.c
hpdf_doc_png.c
        cl -Fosrc\hpdf_ext_gstate.obj -MT -nologo -O2 -Iinclude -Iwin32\include -I"../../libpng"\include -I"../../zlib"\include -c src\hpdf_ext_gstate.c
hpdf_ext_gstate.c
        cl -Fosrc\hpdf_namedict.obj -MT -nologo -O2 -Iinclude -Iwin32\include -I"../../libpng"\include -I"../../zlib"\include -c src\hpdf_namedict.c
hpdf_namedict.c
        cl -Fosrc\hpdf_3dmeasure.obj -MT -nologo -O2 -Iinclude -Iwin32\include -I"../../libpng"\include -I"../../zlib"\include -c src\hpdf_3dmeasure.c
hpdf_3dmeasure.c
        cl -Fosrc\hpdf_exdata.obj -MT -nologo -O2 -Iinclude -Iwin32\include -I"../../libpng"\include -I"../../zlib"\include -c src\hpdf_exdata.c
hpdf_exdata.c
        cl -Fosrc\hpdf_u3d.obj -MT -nologo -O2 -Iinclude -Iwin32\include -I"../../libpng"\include -I"../../zlib"\include -c src\hpdf_u3d.c
hpdf_u3d.c
        cl -Fosrc\hpdf_pdfa.obj -MT -nologo -O2 -Iinclude -Iwin32\include -I"../../libpng"\include -I"../../zlib"\include -c src\hpdf_pdfa.c
hpdf_pdfa.c
        if exist *.lib del *.lib
        lib -out:libhpdf.lib src\hpdf_utils.obj  src\hpdf_error.obj  src\hpdf_mmgr.obj  src\hpdf_list.obj  src\hpdf_streams.obj  src\hpdf_objects.obj  src\hpdf_null.obj  src\hpdf_boolean.obj  src\hpdf_number.obj  src\hpdf_real.obj  src\hpdf_name.obj  src\hpdf_array.obj  src\hpdf_dict.obj  src\hpdf_xref.obj  src\hpdf_encoder.obj  src\hpdf_string.obj  src\hpdf_binary.obj  src\hpdf_encrypt.obj  src\hpdf_encryptdict.obj  src\hpdf_fontdef.obj  src\hpdf_fontdef_tt.obj  src\hpdf_fontdef_type1.obj  src\hpdf_fontdef_base14.obj  src\hpdf_fontdef_cid.obj  src\hpdf_font.obj  src\hpdf_font_type1.obj  src\hpdf_font_tt.obj  src\hpdf_font_cid.obj  src\hpdf_doc.obj  src\hpdf_info.obj  src\hpdf_catalog.obj  src\hpdf_page_label.obj src\hpdf_gstate.obj  src\hpdf_pages.obj  src\hpdf_page_operator.obj  src\hpdf_destination.obj  src\hpdf_annotation.obj  src\hpdf_outline.obj  src\hpdf_image.obj  src\hpdf_encoder_jp.obj  src\hpdf_encoder_kr.obj  src\hpdf_encoder_cns.obj  src\hpdf_encoder_cnt.obj  src\hpdf_fontdef_jp.obj  src\hpdf_fontdef_kr.obj  src\hpdf_fontdef_cns.obj  src\hpdf_fontdef_cnt.obj  src\hpdf_encoder_utf.obj  src\hpdf_image_png.obj  src\hpdf_image_ccitt.obj  src\hpdf_doc_png.obj  src\hpdf_ext_gstate.obj  src\hpdf_namedict.obj  src\hpdf_3dmeasure.obj  src\hpdf_exdata.obj  src\hpdf_u3d.obj  src\hpdf_pdfa.obj
Microsoft (R) Library Manager Version 14.33.31629.0
Copyright (C) Microsoft Corporation.  All rights reserved.
```
But when I try to compile my code I get `unresolved external`  errors, when I use `HPDF_Page_SetRGBStroke(page, 0.0, 0.0, 0.5);` for example.
I noticed I get slightly different error when compiling for release and different for debug version:
Release:

![image](https://user-images.githubusercontent.com/18421898/192132497-531c1104-b16b-42c2-b8ed-0dd81f1ef4d9.png)

Debug:

![image](https://user-images.githubusercontent.com/18421898/192132523-3f792faf-0c77-49f1-9cae-3e83528143bb.png)

I understand the installation instructions are not complete. 
I will try to follow this issue: https://github.com/libharu/libharu/issues/135 , where @Tieske909090 had the same issue with me and managed to fix it,
and this issue: https://github.com/libharu/libharu/issues/208 as I might have forgotten to include some of the libs.

I want to ask, is there any difference when building with Cmake VS building with Nmake?
And, why do I get different error for release and for debug?

**Comment by bramton** [comment]
`unresolved external` errors usually indicate that the library is not specified. Could you verify if the libhpdf library is specified as a library to link against?

**Comment by Basilisvirus** [comment]
Give me some time, I found out I didn't compile the Zlib and pnglib correctly. Thanks to  @Tieske909090 from issue" https://github.com/libharu/libharu/issues/135 I managed to compile the Zlib and pnglibs, and I will proceed with compiling libharu in the next days.

**Comment by Basilisvirus** [comment]
Managed to fix it and sucesfully compile the library. I will be uploading instructions soon.

**Comment by Basilisvirus** [comment]
I followed @Tieske909090 's notes, managed to compile the library and updated the notes into pdfs:

[Zlib Compile how to.pdf](https://github.com/libharu/libharu/files/9779398/Zlib.Compile.how.to.pdf)
[libpng Compile how to.pdf](https://github.com/libharu/libharu/files/9779399/libpng.Compile.how.to.pdf)
[libharu Compile how to.pdf](https://github.com/libharu/libharu/files/9779424/libharu.Compile.how.to.pdf)
