### ISSUE TITLE
Can I use it as a PDF viewer/editor?

### ISSUE THREAD

**Issue by arghanath007** [libharu/libharu#248]
# Can I use it as a PDF viewer/editor?

> Can you guys give some images explaining what does it like and how it can be used. I think that would be easier for people to understand the use of it. Thanks

**Comment by chakani** [comment]
Haru PDF is a low-level library of functions that you call from your program. You draw lines, display text and images, etc. by calling the Haru API. It's very powerful, but a lot of work.

**Comment by arghanath007** [comment]
Oh like a CLI for PDF files?

**Comment by bramton** [comment]
No, its not like a CLI. It's a library which can be used for writing programs which generate PDF files. A quick look in the documentation gives you a feeling about the usage:

https://github.com/libharu/libharu/wiki/Usage-examples

**Comment by arghanath007** [comment]
Thanks for the info guys.
