### ISSUE TITLE
Inconsistent defines for HAVE_ZLIB and HAVE_LIBZ

### ISSUE THREAD

**Issue by karstenBriksoft** [libharu/libharu#249]
I was debugging, why the printed PDFs are relatively big in size and noticed that `HPDF_SetCompressionMode()` returned `HPDF_INVALID_COMPRESSION_MODE` even though i compiled the library with z-lib support. 

Turns out that the library code expects the define `#LIBHPDF_HAVE_ZLIB` but CMAKE produces the define `#LIBHPDF_HAVE_LIBZ` (spelled LibZ vs ZLib). 

I can confirm that fixing the inconsistency indeed allows for successfully setting the compression and results in smaller files.

What i'm not so sure about: which would be the right thing to use? LIBZ is used by libPNG, too. ZLIB would be what was used by libharu previously.

**Comment by bramton** [comment]
Good catch! It seems the majority of the code was using HAVE_ZLIB, hence I renamed the LIBZ references to this as well. I have applied the changes to the devel branch.

**Comment by karstenBriksoft** [comment]
thanks a lot!
