### ISSUE TITLE
fatal error C1083: Cannot open include file: 'hpdf_version.h': No such file or directory

### ISSUE THREAD

**Issue by KylinGuo** [libharu/libharu#250]
I am using VS 2019 on Windows 10. I received this error message when I used nmake command to complie libharu. Here are the screen output. 

// === Begin ===

C:\Users\<User Name>\Desktop\libharu-2.4.2>NMAKE -f script/Makefile.msvc_dll

Microsoft (R) Program Maintenance Utility Version 14.29.30146.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        cl -Fosrc\hpdf_utils.obj /MD -nologo -O2 -Iinclude -Iwin32\include   -I"../../libpng"\include -I"../../zlib"\include -DHPDF_DLL_MAKE -c src\hpdf_utils.c
hpdf_utils.c

(...)

        cl -Fosrc\hpdf_doc.obj /MD -nologo -O2 -Iinclude -Iwin32\include   -I"../../libpng"\include -I"../../zlib"\include -DHPDF_DLL_MAKE -c src\hpdf_doc.c
hpdf_doc.c
src\hpdf_doc.c(27): fatal error C1083: Cannot open include file: 'hpdf_version.h': No such file or directory
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.EXE"' : return code '0x2'
Stop.

// === End ===

**Comment by Basilisvirus** [comment]
I hope this will helo you:
I followed @Tieske909090 's notes, managed to compile the library and updated the notes into pdfs:

[Zlib Compile how to.pdf](https://github.com/libharu/libharu/files/9779398/Zlib.Compile.how.to.pdf)
[libpng Compile how to.pdf](https://github.com/libharu/libharu/files/9779399/libpng.Compile.how.to.pdf)
[libharu Compile how to.pdf](https://github.com/libharu/libharu/files/9779424/libharu.Compile.how.to.pdf)

**Comment by bramton** [comment]
This issue has been resolved with the latest release (2.4.3).
In addition, I would suggest to use cmake for generating the platform dependant makefiles.
