### ISSUE TITLE
Can I get the x,y position where the string I write (with `HPDF_Page_TextOut` for example) ends?

### ISSUE THREAD

**Issue by Basilisvirus** [libharu/libharu#254]
I am writing two strings in the same line (height) of the pdf. 
I want to start writing the `second string`, after the `first string` ends (visually).

![image](https://user-images.githubusercontent.com/18421898/196004875-43d447d3-8260-4189-9cfc-aa3e53c25a6b.png)

The two strings will be of random characters and random length. I tried getting the length of the first string, multiplying it by an fix number to get its visual/drawing length, but it heavily depends on the number of characters used and the visual size of each character.

Trying to study the documentation, I found out that some functions have this "before and after" note under "graphics", I am not sure what this is, for example in the [HPDF_Page_SetTextLeading()](https://github.com/libharu/libharu/wiki/API%3A-Graphics#HPDF_Page_SetTextLeading ) it has `HPDF_GMODE_PAGE_DESCRIPTION `or `HPDF_GMODE_TEXT_OBJECT` . Are these flags, errors? I could find them in the documentation.

![image](https://user-images.githubusercontent.com/18421898/196004968-be2b3261-f870-4751-b924-48399de938e2.png)

Does this anything has to do with the "before and after" visual/xy coordinates position of the text?

Another alternative I could try, is to use: [HPDF_Page_TextRect() ](https://github.com/libharu/libharu/wiki/API%3A-Graphics#HPDF_Page_TextRect )  and keep making the text rectangle larger until the text fits in the rectangle. When the text fits, it will be the position of the last character.

I will check the documentation again, but couldn't spot anything right now. This "before and after" needs more explanation I think.
Thank you in advance.

**Comment by bramton** [comment]
Perhaps [HPDF_Page_TextWidth()](https://github.com/libharu/libharu/wiki/API%3A-Page#hpdf_page_textwidth) can be of use?
