### ISSUE TITLE
undefined reference to HPDF_Direct_Free & HPDF_Direct_Write

### ISSUE THREAD

**Issue by KuMo2018** [libharu/libharu#257]
-----------------------------------------------------------------------------------------------
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

D:\PDF\libharu>mingw32-make -f script/Makefile.mingw demo
gcc -o demo/encoding_list.exe -Iinclude -O2 -Wall   demo/encoding_list.c  -Lwin3
2/mingw -L. -lhpdf -lpng -lz
./libhpdf.a(hpdf_objects.o):hpdf_objects.c:(.text+0x21): undefined reference to
`HPDF_Direct_Free'
./libhpdf.a(hpdf_objects.o):hpdf_objects.c:(.text+0xfd): undefined reference to
`HPDF_Direct_Write'
collect2.exe: error: ld returned 1 exit status
mingw32-make: *** [script/Makefile.mingw:145: demo/encoding_list.exe] Error 1

D:\PDF\libharu>
-------------------------------------------------------------------------------------------------
undefined reference to HPDF_Direct_Free & HPDF_Direct_Write   Why？
There are two functions in hpdf_direct.c

**Comment by lyy1119** [comment]
怎么解决的？我也遇到这个问题了
编译指令g++ -std=c++17 main.cpp -static -O2 -Wall -o pngs2pdf -lhpdf -lpng -lz -lm -lstdc++
