### ISSUE TITLE
hpdf_encoder_utf.c is not compiled by default

### ISSUE THREAD

**Issue by lelandyang** [libharu/libharu#260]
It has been a long existing bug that UTF-8 encoding support (hpdf_encoder_utf.c) is shipped with the source code while neither the makefile nor CMake comes with hpdf_encoder_utf.c compilation option.
It is therefore strongly suggested to add the file to CMakefile list by default .

**Comment by bramton** [comment]
Good point. It has been added now to the CMake file.
