### ISSUE TITLE
Error building for macOS Catalina: ld: symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by daryl-williams** [libharu/libharu#261]
Hello There,

I have built libharu on an M1 MacBook from the git repository and it compiled without any issues, however I am now trying to use the library from an application I am writing and I am getting the following build error and I am unable to determine where those symbols are defined. Any help would be greatly appreciated.

ld: symbol(s) not found for architecture arm64

for the following symbols:

Undefined symbols for architecture arm64:
  "_HPDF_AddPage", referenced from:
      _GenPDFpage in song2pdf-83808c.o
  "_HPDF_Free", referenced from:
      _GenPDFdoc in song2pdf-83808c.o
  "_HPDF_GetFont", referenced from:
      _GenPDFdoc in song2pdf-83808c.o
  "_HPDF_GetStreamSize", referenced from:
      _PDFdoc2stdout in song2pdf-83808c.o
  "_HPDF_New", referenced from:
      _GenPDFdoc in song2pdf-83808c.o
  "_HPDF_Page_BeginText", referenced from:
      _Wt_lmss_keyof in song2pdf-83808c.o
      _GenPDFpage in song2pdf-83808c.o
  "_HPDF_Page_EndText", referenced from:
      _GenPDFpage in song2pdf-83808c.o
  "_HPDF_Page_GetHeight", referenced from:
      _Wt_lmss_keyof in song2pdf-83808c.o
      _GenPDFpage in song2pdf-83808c.o
  "_HPDF_Page_SetFontAndSize", referenced from:
      _GenPDFpage in song2pdf-83808c.o
  "_HPDF_Page_SetRGBFill", referenced from:
      _Wt_lmss_keyof in song2pdf-83808c.o
      _GenPDFpage in song2pdf-83808c.o
  "_HPDF_Page_SetSize", referenced from:
      _GenPDFpage in song2pdf-83808c.o
  "_HPDF_Page_ShowText", referenced from:
      _Wt_lmss_keyof in song2pdf-83808c.o
      _GenPDFpage in song2pdf-83808c.o
  "_HPDF_Page_TextOut", referenced from:
      _Wt_lmss_keyof in song2pdf-83808c.o
      _GenPDFpage in song2pdf-83808c.o
  "_HPDF_ReadFromStream", referenced from:
      _PDFdoc2stdout in song2pdf-83808c.o
  "_HPDF_ResetStream", referenced from:
      _PDFdoc2stdout in song2pdf-83808c.o
  "_HPDF_SaveToFile", referenced from:
      _GenPDFdoc in song2pdf-83808c.o
  "_HPDF_SaveToStream", referenced from:
      _PDFdoc2stdout in song2pdf-83808c.o
  "_HPDF_SetCompressionMode", referenced from:
      _GenPDFdoc in song2pdf-83808c.o
  "_HPDF_SetInfoAttr", referenced from:
      _InsertPDFtitle in song2pdf-83808c.o
ld: symbol(s) not found for architecture arm64

Thanks and Best Regards,

Daryl

**Comment by bramton** [comment]
Make sure you are linking agains the libhpdf.so library.
