### ISSUE TITLE
typos in fontdefs

### ISSUE THREAD

**Issue by lhf** [libharu/libharu#264]
hpdf_fontdef_jp.c:1688:    if ((ret = HPDF_CIDFontDef_AddWidth (fontdef, MS_Gothic_W_ARRAY)) !=
MS_Gothic_W_ARRAY should be MS_Mincho_W_ARRAY

hpdf_fontdef_jp.c:1749:    if ((ret = HPDF_CIDFontDef_AddWidth (fontdef, MS_PGothic_W_ARRAY)) !=
MS_PGothic_W_ARRAY should be MS_PMincho_W_ARRAY

hpdf_fontdef_kr.c:1356:    if ((ret = HPDF_CIDFontDef_AddWidth (fontdef, DotumChe_W_ARRAY)) !=
DotumChe_W_ARRAY should be BatangChe_W_ARRAY

hpdf_fontdef_kr.c:1417:    if ((ret = HPDF_CIDFontDef_AddWidth (fontdef, Dotum_W_ARRAY)) !=
Dotum_W_ARRAY should be Batang_W_ARRAY

**Comment by bramton** [comment]
Thanks. For future engagement: a pull request is much appreciated!

Personal note: relates to #43
