### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by ChenKe404** [libharu/libharu#268]
1.How do I add layers to a page? like pdflib function : "PDF_define_layer"
2.How do I tanslate coordinate origin? like pdflib function : "PDF_translate"
3.How do I scale coordinate system? like pdflib function : "PDF_scale"
4.How do I rotate coordinate system? like pdflib function : "PDF_rotate"

**Comment by bramton** [comment]
Please have a look at the documentation:
https://github.com/libharu/libharu/wiki

Also the `demo` directory provides a lot of examples.

**Comment by ChenKe404** [comment]
> Please have a look at the documentation: https://github.com/libharu/libharu/wiki
> 
> Also the `demo` directory provides a lot of examples.

sorry, I don't find any about layer's api or description from documentation and source code.

**Comment by ChenKe404** [comment]
the "layer" mean is : i can draw something on one page, and i can draw some of them to different layer, then i can set some layer "show" or "hidden"  , that make me easy to see what I need to pay attention to. sorry about my english.

**Comment by ChenKe404** [comment]
This feature is well implemented by pdflib, and is well supported by WPS and Adobe PDF.
