### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by kpsilenc5** [libharu/libharu#269]
当我在使用libharu库编写代码时，总有：
 error C3861: “HPDF_ReadFromFile”: 找不到标识符
error C3861: “HPDF_GetPageCount”: 找不到标识符
error C3861: “HPDF_GetPage”: 找不到标识符
 error C3861: “HPDF_Page_Copy”: 找不到标识符
这些报错，请问我该怎么解决这个问题呢

**Comment by bramton** [comment]
My Chinese is not that good, could you provide an English description?

**Comment by ChenKe404** [comment]
> 

he say: got some function "can't found symbol" error , i think he haven't included header correctly

**Comment by bramton** [comment]
Agreed, I also think it is related to a missing header file.
