### ISSUE TITLE
HPDF_Page_TextRect  Special character (German Umlaut) not display properly 

### ISSUE THREAD

**Issue by patelmaurya** [libharu/libharu#27]
I am using libharu for iPad pdf functionality and i want to display german text (specially Umlaut characters) on pdf using HPDF_Page_TextRect. i have tried various combinations in code but not get success to display  umlaut characters (üöäÄÜÖß).

If you have any solution for my issue please provide me.

**Comment by anhtuantt** [comment]
Hello everyone,
I'm using Libharu to generate PDF report that support Chinese language. Everything is fine if only one Chinese font is embedded. But i got the error at embedding the second Chinese font. The first time:
 	HPDF_LoadTTFontFromFile(outputFile, "c:/Windows/fonts/msyh.ttf", HPDF_TRUE);
everything is OK, the Chinese language is correctly displayed.
After that, i embed the second font (BOLD version)
HPDF_LoadTTFontFromFile(outputFile, "c:/Windows/fonts/msyhbd.ttf", HPDF_TRUE), the problem gets the exception with error code 0x1025 HPDF_INVALID_DOCUMENT with that command.
Please give me any advice or solution.

**Comment by daB0bby** [comment]
This is my solution working perfectly with UTF-8:

```cpp
HPDF_UseUTFEncodings(_pdf);
auto font = HPDF_LoadTTFontFromFile(_pdf, (_pathToAssets + "calibri.ttf").data(), HPDF_TRUE);
_font = HPDF_GetFont(_pdf, font, "UTF-8");
```

**Comment by whidbey** [comment]
is this closed?
