### ISSUE TITLE
PDF has garbled text when copy pasting (UTF-8)

### ISSUE THREAD

**Issue by uebelack** [libharu/libharu#290]
Looks like things have slowed down here, but I'll give it a shot anyway.

When I use utf8 encoding for the PDF, it looks fine on the pdf. However, when I try to copy and paste the text from the PDF, the text is broken:

<img width="1113" alt="Screenshot 2023-09-14 at 10 59 51" src="https://github.com/libharu/libharu/assets/1791995/4e5596fa-9155-4770-aa63-d29f6b89cd49">

I'm not really experienced with PDFs and C, so I'm hoping someone here can help out.

I have at least added a demo with which you can reproduce the problem: 

https://github.com/uebelack/libharu/commit/9fddb602e42d6ff1e9c8f348186e731ec863261b

**Comment by bramton** [comment]
I just tried the demo code provided by you, and it works fine. Also the copy pasting. Could you try it with a differente PDF viewer/OS ?

**Comment by uebelack** [comment]
Thanks for looking into this. Just tested it with Adobe Acrobat Reader, and there it works without problems. So it looks like a bug in the macOS preview ;-).
