### ISSUE TITLE
Problem with Demos and Latest release

### ISSUE THREAD

**Issue by samsonsite1** [libharu/libharu#294]
I'm having an issue with the latest libharu release (v2.4.4?).  I've compiled the demos and they run without errors, however when I try to view the PDF file that the demo created, using Adobe Reader, it comes up blank.

I don't know how to verify or validate the PDF file.  I tried using this tool, pdfinfo.exe, from xpdf-tools, and it says the page size is zero:

Producer:       Haru Free PDF Library 2.4.4
Tagged:         no
Form:           none
Pages:          1
Encrypted:      no
Page size:      0 x 0 pts (rotated 0 degrees)
File size:      14714 bytes
Optimized:      no
PDF version:    1.3

Compared to the old demo PDF file:

Producer:       Haru Free PDF Library 2.0.6
Tagged:         no
Form:           none
Pages:          1
Encrypted:      no
Page size:      550 x 650 pts (rotated 0 degrees)
File size:      13476 bytes
Optimized:      no
PDF version:    1.3

BTW, some demos have compiler errors, as they haven't been updated, like the line_demo is still passing HPDF_UINT16 parameters instead of HPDF_REAL for HPDF_Page_SetDash().

What else can I do to verify PDF files written by libharu?  Because something has changed,  and I don't know where to look.

**Comment by samsonsite1** [comment]
Ok, I opened up the PDF file as text, and noticed the MediaBox line is being written as all zero:

/Type /Page
/MediaBox [ 0 0 0 0 ]

I don't see how this is possible, because even if the demo isn't calling HPDF_Page_SetWidth() or HPDF_Page_SetHeight(), MediaBox is filled with HPDF_DEF_PAGE_WIDTH, HPDF_DEF_PAGE_HEIGHT when a new page is created.

So, what is going on with v2.4.4?  Why isn't it writing out the page dimensions?

**Comment by samsonsite1** [comment]
BTW, I'm on a Windows platform and I'm using script\Makefile.msvc to compile libharu.

Some other minor issues:

I had to add the following source code file to Makefile.msvc, which is apparently missing:

	src\hpdf_direct.obj \

**Comment by samsonsite1** [comment]
Found the issue.  HPDF_FToA is buggy.

**Comment by dmitrys99** [comment]
> Found the issue. HPDF_FToA is buggy.

What bug did you find?

**Comment by dmitrys99** [comment]
> What are people doing to compile this library if it hasn't been maintained for so long?

Library need some love, sure.
If you're able to revive build files for Windows, at least create PR for it.

**Comment by samsonsite1** [comment]
HPDF_FToA() is responsible for convert floating-point numbers to ascii text.  For some unknown reason, this function becomes corrupt when compiled on Windows platform, so MediaBox gets written out as all zero, and Adobe Reader thinks the page is blank.

Somebody changed it years ago, but something about it is causing a stack corruption.

I reverted it back to an older version:
https://github.com/libharu/libharu/issues/295

**Comment by bramton** [comment]
@samsonsite1 could you provide a bit more details on your Windows platform ? What architecture are you using and which compiler?

> What are people doing to compile this library if it hasn't been maintained for so long?
There is an [vcpkg](https://vcpkg.io) available and at least Microsoft Visual Studio has CMake support.

**Comment by samsonsite1** [comment]
I was preparing a test, and discovered the root of my problem.

When I was compiling the library again, I noticed some compiler warnings:

1>hpdf_utils.c(226) : warning C4013: 'log10' undefined; assuming extern returning int
1>hpdf_utils.c(235) : warning C4013: 'modff' undefined; assuming extern returning int

I think I was getting stack corruption because these functions weren't getting linked.

Both log10() and modff() are new functions that were added, and they require the header file <math.h>.

In "hpdf_utils.h", this has the line #include "hpdf_config.h".  However, this points
to a win32 generated config file with a lot of defines, no headers.  It doesn't contain <math.h>.

The actual <math.h> header is found here:
"hpdf_conf.h"

So, did someone make a typo mistake by including "hpdf_config.h" instead of "hpdf_conf.h"
in hpdf_utils.c ?

But, anyway, I manually added #include <math.h> to hpdf_utils.c, and that fixed my problem.

Perhaps these two config files need better names to avoid this mistake in the future.

**Comment by bramton** [comment]
It seems the `math.h` header file is just included in the `hpdf_utils.c` file.
https://github.com/libharu/libharu/blob/0c598becaadaef8e3d12b883f9fc2864a118c12d/src/hpdf_utils.c#L18

> So, did someone make a typo mistake by including "hpdf_config.h" instead of "hpdf_conf.h"
in hpdf_utils.c ?

No. This is correct. Some of the debug macros defined in `hpdf_utils.h` depend on the values from the `hpdf_config.h` file.
