### ISSUE TITLE
Soft Mask Image Problem (SMask)

### ISSUE THREAD

**Issue by samsonsite1** [libharu/libharu#297]
I'm having a problem with viewing PNG files with transparency. 

I can create a PDF file without errors, but when I view the PDF file in Adobe Reader, the colors
of the image are slightly darkened.  For example, solid red (255,0,0), turns into a muted red (238,31,37).

This only happens when the PNG file has transparency.  If I remove the transparency, it draws solid colors again.

I compiled the libharu demos, and ran png_demo.c, which loads PNG files with various transparencies.
And the same issue happens with the demo. I get muted colors.

Has anyone experienced this before?

**Comment by samsonsite1** [comment]
Here's what I see in Adobe Reader:

![COLORS](https://github.com/libharu/libharu/assets/7414478/39edb084-45f2-4da4-aefa-50c054cf2b0a)

**Comment by o2solutions-support** [comment]
Can you post a link to the PDF file displayed in the screenshot above and also the input PDF images?

**Comment by samsonsite1** [comment]
[colors_24bit.pdf](https://github.com/libharu/libharu/files/12969451/colors_24bit.pdf)
[colors_32bit.pdf](https://github.com/libharu/libharu/files/12969456/colors_32bit.pdf)
![colors_24bit](https://github.com/libharu/libharu/assets/7414478/a0710c7e-b86a-4c5d-a171-4c2f89a925e8)
![colors_32bit](https://github.com/libharu/libharu/assets/7414478/d7edee9f-6b44-422a-9587-2d6d968254ca)

does this work?  attached to message.

**Comment by o2solutions-support** [comment]
This is how the files are displayed on our computers using the latest version of Acrobat:
![rgb](https://github.com/libharu/libharu/assets/77455387/1f36783a-cdbe-433c-a964-72f56fa1c930)
The colors are the same in both files and both PDF files are correct (there is no problem with the PDF files).
This issue might be related to the version of Adobe Acrobat/Reader you use. In the past, when transparency was involved, Acrobat/Reader used a different rendering pipeline and colors were a bit different.

**Comment by samsonsite1** [comment]
If my version of Adobe Reader has problems showing a 32-bit PNG file, then shouldn't it have
problems with all such examples?

The sample file, png_demo.pdf, that comes with the demo, has embedded 32-bit PNG files, and this 
displays correctly in my Adobe Reader.

pngsuite\basn4a08.png
pngsuite\basn4a16.png
pngsuite\basn6a08.png
pngsuite\basn6a16.png

However, if I recompile this demo and run it, Adobe Reader shows muted colors.

I tried to compare the two PDF files, there are some minor differences, but I don't see anything obvious.

The PDF file format specs say transparency wasn't officially supported until PDF v1.4. 
libharu is writing out files as PDF-1.3, so I edited the file as PDF-1.4.  But, it still didn't work.

[png_demo_ORIG.pdf](https://github.com/libharu/libharu/files/13039892/png_demo_ORIG.pdf)
[png_demo_BAD.pdf](https://github.com/libharu/libharu/files/13039894/png_demo_BAD.pdf)

**Comment by o2solutions-support** [comment]
png_demo_ORIG.pdf - the images have no transparency, they have no soft mask attached
png_demo_BAD.pdf - the images have transparency, they have a soft mask attached
The original PNG images probably have transparency in them but this is not reflected in png_demo_ORIG.pdf.
However, when you recompile the demo and run it, they are processed correctly and the transparency is kept, thus the results you see.

**Comment by samsonsite1** [comment]
Ah, I see.  The code for the PNG loader was changed since the last demo version.  The SMask tag isn't even in the old PDF file.

**Comment by o2solutions-support** [comment]
Usually PDF libraries let you set the PDF version you want in the PDF file no matter what PDF features you use. Unless you have an edge case with strict PDF validation rules, PDF processors that load PDF files process what they know in the PDF file and ignore the PDF version set in the file. So if your image has a /SMask, the PDF processors will handle it no matter the PDF version in the file is 1.0 or 1.7.
