### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by ajaimesv** [libharu/libharu#30]
Hi, I downloaded the tar.gz file from http://libharu.org/. When looking for a "configure" file, there's none. I tried buildconf.sh and think I got a good one, however, I now can't find a Makefile...

I was following the "configure && make && make install" instructions.

Thank you.
By the way, I'm on linux/gcc

**Comment by Nadya678** [comment]
Can anyone help me with it?

Cygwin:
![obraz](https://user-images.githubusercontent.com/31185239/29684026-c0501b10-8910-11e7-9801-d54110107d3f.png)

**Comment by dpethes** [comment]
@Nadya678 you need GNU make.
