### ISSUE TITLE
DashMode is HPDF_REAL in the sources, but HPDF_UINT16 in the line_demo.c file

### ISSUE THREAD

**Issue by ignaciordc** [libharu/libharu#314]
In **hpdf_page_operator.c** we have:

```
HPDF_Page_SetDash  (HPDF_Page        page,
                    const HPDF_REAL *dash_ptn,
                    HPDF_UINT        num_param,
                    HPDF_REAL        phase)
```

but then in **demo\line_demo.c**
```
const HPDF_UINT16 DASH_MODE1[] = {3};
...
HPDF_Page_SetDash (page, DASH_MODE1, 1, 1);

```
Types for the dash differ

**Comment by samsonsite1** [comment]
I'm sure you have already figured it out by now.  API changed, but some things weren't updated.

`
    //const HPDF_UINT16 DASH_MODE1[] = {3};
    //const HPDF_UINT16 DASH_MODE2[] = {3, 7};
    //const HPDF_UINT16 DASH_MODE3[] = {8, 7, 2, 7};

    const HPDF_REAL DASH_MODE1[] = {3.0};
    const HPDF_REAL DASH_MODE2[] = {3.0, 7.0};
    const HPDF_REAL DASH_MODE3[] = {8.0, 7.0, 2.0, 7.0};
`
