### ISSUE TITLE
Static library is not built

### ISSUE THREAD

**Issue by timtas** [libharu/libharu#318]
Hi all
I tried to build current libharu (2.4.4) as a static library, but while such an option exists, it seems it is ignored.

I tried building with:

`-DBUILD_SHARED_LIBS=ON -DBUILD_STATIC_LIBS=ON -DLIBHPDF_SHARED=ON -DLIBHPDF_STATIC=ON 
`

**Comment by bramton** [comment]
The CMake file was a bit confusing with some unused variabled. This has been cleaned up. To build the static library add this flag to cmake: `-DBUILD_SHARED_LIBS=OFF`
