### ISSUE TITLE
error_no 1017 detail_no 22

### ISSUE THREAD

**Issue by earlyfielder** [libharu/libharu#325]
What causes this error?
It seems to occur depending on the environment, but the cause cannot be determined.
Can someone please elaborate on this?

**Comment by lhf** [comment]
hpdf_error.h tells you that error_no 1017 is HPDF_FILE_OPEN_ERROR.
detail_no 22 comes from the OS errno and is most probably "Invalid argument".

**Comment by earlyfielder** [comment]
@lhf 
Thanks for your reply! 
I will look into it based on that information.
