### ISSUE TITLE
How do I start using Haru library?

### ISSUE THREAD

**Issue by MonikaTopiwala** [libharu/libharu#49]
I would like to create pdf file using C.
I installed haru library as per the installation step.

But I could not able to build sample code in Ubuntu12.04.
I use command to run sample code is ,

gcc-o result.o test_code.c

I found following error,
/tmp/ccCzocHH.o: In function `main':
test_code.c:(.text+0xbf): undefined reference to`HPDF_New'
test_code.c:(.text+0xfc): undefined reference to `HPDF_Free'
test_code.c:(.text+0x112): undefined reference to`HPDF_AddPage'
test_code.c:(.text+0x122): undefined reference to `HPDF_Page_GetHeight'
test_code.c:(.text+0x132): undefined reference to`HPDF_Page_GetWidth'
test_code.c:(.text+0x14b): undefined reference to `HPDF_Page_SetLineWidth'
test_code.c:(.text+0x18b): undefined reference to`HPDF_Page_Rectangle'
test_code.c:(.text+0x197): undefined reference to `HPDF_Page_Stroke'
test_code.c:(.text+0x1b3): undefined reference to`HPDF_GetFont'
test_code.c:(.text+0x1d4): undefined reference to `HPDF_Page_SetFontAndSize'
test_code.c:(.text+0x1e8): undefined reference to`HPDF_Page_TextWidth'
test_code.c:(.text+0x1f8): undefined reference to `HPDF_Page_BeginText'
test_code.c:(.text+0x232): undefined reference to`HPDF_Page_TextOut'
test_code.c:(.text+0x23e): undefined reference to `HPDF_Page_EndText'
test_code.c:(.text+0x24a): undefined reference to`HPDF_Page_BeginText'
test_code.c:(.text+0x267): undefined reference to `HPDF_Page_SetFontAndSize'
test_code.c:(.text+0x294): undefined reference to`HPDF_Page_TextOut'
test_code.c:(.text+0x2a0): undefined reference to `HPDF_Page_EndText'
test_code.c:(.text+0x2ac): undefined reference to`HPDF_Page_BeginText'
test_code.c:(.text+0x2d1): undefined reference to `HPDF_Page_MoveTextPos'
test_code.c:(.text+0x309): undefined reference to`HPDF_GetFont'
test_code.c:(.text+0x32a): undefined reference to `HPDF_Page_SetFontAndSize'
test_code.c:(.text+0x345): undefined reference to`HPDF_Page_ShowText'
test_code.c:(.text+0x363): undefined reference to `HPDF_Page_MoveTextPos'
test_code.c:(.text+0x380): undefined reference to`HPDF_Page_SetFontAndSize'
test_code.c:(.text+0x394): undefined reference to `HPDF_Page_ShowText'
test_code.c:(.text+0x3b2): undefined reference to`HPDF_Page_MoveTextPos'
test_code.c:(.text+0x3d6): undefined reference to `HPDF_Page_EndText'
test_code.c:(.text+0x3ea): undefined reference to`HPDF_SaveToFile'
test_code.c:(.text+0x3f6): undefined reference to `HPDF_Free'
collect2: ld returned 1 exit status

can anybody help me?

**Comment by myd7349** [comment]
Maybe you should add the `-l` option to link your code against with libharu(`-lharu`, for instance).

**Comment by tony2001** [comment]
-lhpdf, yes.
