### ISSUE TITLE
Missing configure script

### ISSUE THREAD

**Issue by Maliuta** [libharu/libharu#51]
The source code tree is missing the configure script for Linux.

**Comment by jgm** [comment]
Quoting https://github.com/libharu/libharu/wiki/Installation:

> If the `./configure` script is missing (which is the case for Git checkouts and Github tarballs), run `./buildconf.sh` script to generate it. You'll need autoconf, automake and libtool packages installed to do that.

**Comment by Nadya678** [comment]
It doesn't help on Cygwin  2.8.2(0.313/5/3) 2017-07-12 10:53 i686. I cannot create configure script.
