### ISSUE TITLE
Font name in jpfont_demo.c is incorrect.

### ISSUE THREAD

**Issue by ankurpawar** [libharu/libharu#53]
The font name MS-Mincyo and MS-PMincyo in file /libharu/demo/jpfont_demo.c is giving exception. It should be MS-Mincho and MS-PMincho.

**Comment by eldesh** [comment]
I also get an error with executing jpfont_demo.

> build/demo$ ./jpfont_demo
> ERROR: error_no=102F, detail_no=0

**Comment by bramton** [comment]
Fixed by PR #25 and PR #80.
