### ISSUE TITLE
Compile error in libharu

### ISSUE THREAD

**Issue by usernamethatisnottaken** [libharu/libharu#72]
I am using bcc32 and have been able to compile and link libhpdf.dll
However, when I try to run the makefile with the "demo" switch, I get an error:

Error E2303 include\hpdf.h 464: Type name expected

File hpdf.h:
459         HPDF_EXPORT(HPDF_XObject)
460         HPDF_Page_CreateXObjectFromImage    (HPDF_Doc       pdf,
461                                     HPDF_Page      page,
462                                     HPDF_Rect      rect,
463                                     HPDF_Image     image,
464                                     HPDF_Boolean   zoom);

HPDF_Boolean is defined in hpdf_objects.h as a pointer to a structure:

typedef struct _HPDF_Boolean_Rec  *HPDF_Boolean;

typedef struct _HPDF_Boolean_Rec {
    HPDF_Obj_Header  header;
    HPDF_BOOL        value;
} HPDF_Boolean_Rec;

What is wrong here?

**Comment by mathstuf** [comment]
I think that the `#ifdef HPDF_SHARED` side of the `typedef` just needs to add `typedef HPDF_HANDLE_HPDF_Boolean` to it.

**Comment by bramton** [comment]
Fixed by #189
